id: PA41736A7
initial_creation_type: ocr
source_metadata:
  volumes:
    800d3a2523374730986a79fedb82b7a7:
      base_file: v098.txt
      image_group_id: I1PD95943
      title: རྩོད་པའི་རིགས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1825
      volume_number: 98
